#ifndef _BLOCK_TYPE_H_
#define _BLOCK_TYPE_H_

static const s32 BLOCK_TYPE_COUNT = 16;
static const s32 DOOR_TYPE_COUNT = 7;
static const s32 BOULDER_TYPE_COUNT = 7;
static const s32 WALL_TYPE_COUNT = 20;
static const s32 SOIL_TYPE_COUNT = 10;

enum BlockType {
	BLOCK_TYPE_NULL = 0,
	BLOCK_TYPE_PLAYER = 1,
	BLOCK_TYPE_DIAMOND = 2,
	BLOCK_TYPE_BUBBLE = 3,
	BLOCK_TYPE_FIRE = 4,
	BLOCK_TYPE_BEAN = 5,
	BLOCK_TYPE_GRAVITY = 6,
	BLOCK_TYPE_EXTRA_LIFE = 7,
	BLOCK_TYPE_BARRIER = 8,
	BLOCK_TYPE_BARRIER_CONTROL = 9,
	BLOCK_TYPE_TELEPORT = 10,
	BLOCK_TYPE_DOOR = 11,
	BLOCK_TYPE_BOULDER = 12,
	BLOCK_TYPE_WALL = 13,
	BLOCK_TYPE_SOIL = 14,
	BLOCK_TYPE_SOIL_WET = 15
};

enum DoorType {
	DOOR_TYPE_WHITE = 0,
	DOOR_TYPE_RED = 1,
	DOOR_TYPE_GREEN = 2,
	DOOR_TYPE_BLUE = 3,
	DOOR_TYPE_CYAN = 4,
	DOOR_TYPE_MAGENTA = 5,
	DOOR_TYPE_YELLOW = 6
};

enum BoulderType {
	BOULDER_TYPE_WHITE = 0,
	BOULDER_TYPE_RED = 1,
	BOULDER_TYPE_GREEN = 2,
	BOULDER_TYPE_BLUE = 3,
	BOULDER_TYPE_CYAN = 4,
	BOULDER_TYPE_MAGENTA = 5,
	BOULDER_TYPE_YELLOW = 6
};

enum WallType {
	WALL_TYPE_BRICK_WHITE = 0,
	WALL_TYPE_BRICK_RED = 1,
	WALL_TYPE_BRICK_GREEN = 2,
	WALL_TYPE_BRICK_BLUE = 3,
	WALL_TYPE_BRICK_CYAN = 4,
	WALL_TYPE_BRICK_YELLOW = 5,
	WALL_TYPE_BRICK_MAGENTA = 6,
	WALL_TYPE_ROCK = 7,
	WALL_TYPE_ICE = 8,
	WALL_TYPE_METAL = 9,
	WALL_TYPE_BRAIN = 10,
	WALL_TYPE_GIRDER = 11,
	WALL_TYPE_HEART = 12,
	WALL_TYPE_HONEYCOMB = 13,
	WALL_TYPE_LEAFY = 14,
	WALL_TYPE_NUCLEAR = 15,
	WALL_TYPE_PIPE = 16,
	WALL_TYPE_QUESTION = 17,
	WALL_TYPE_SAND = 18,
	WALL_TYPE_SQUARE = 19
};

enum SoilType {
	SOIL_TYPE_WHITE = 0,
	SOIL_TYPE_RED = 1,
	SOIL_TYPE_GREEN = 2,
	SOIL_TYPE_BLUE = 3,
	SOIL_TYPE_CYAN = 4,
	SOIL_TYPE_MAGENTA = 5,
	SOIL_TYPE_YELLOW = 6,
	SOIL_TYPE_HONEYCOMB = 7,
	SOIL_TYPE_QUESTION = 8,
	SOIL_TYPE_BOULDER = 9
};

#endif